apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: obsqf16pm-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-springboot:github-5b1b2008ff51d19f315969c781c0850ab0e9af11
          name: container-image
