apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: obsqf16pm-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/obsqf16pm-java-springboot-gitops